/**
* Pictural API
* This API is part of my project for the Shopify Developer intern challenge. This API manage the users, pictures and links between accounts of Pictural.
*
* The version of the OpenAPI document: 0.1.0
* Contact: chretienxavier42@gmail.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.xavierc.pictural.api.models

import dev.xavierc.pictural.api.models.Friend
import dev.xavierc.pictural.api.models.ImageInfo
import java.util.*

/**
 * 
 * @param uuid UUID of the album
 * @param title Title of the album
 * @param ownerUuid Uuid of the owner of the album
 * @param images Images of this album
 * @param friends List of the friend that can access this album
 */
data class Album (
    /* UUID of the album */
    val uuid: UUID,
    /* Owner of the album */
    val ownerUuid: String,
    /* Title of the album */
    val title: String,
    /* Images of this album */
    val images: List<UUID>,
    /* List of the friend that can access this album */
    val friends: List<Friend>
) 

