/**
* Pictural API
* This API is part of my project for the Shopify Developer intern challenge. This API manage the users, pictures and links between accounts of Pictural.
*
* The version of the OpenAPI document: 0.1.0
* Contact: chretienxavier42@gmail.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.xavierc.pictural.api.models


/**
 * 
 * @param uuid UUID of the friend
 * @param name Name of the user
 * @param pictureUuid Url of the profile picture of the friend
 */
data class Friend (
    /* UUID of the friend */
    val uuid: java.util.UUID,
    /* Name of the user */
    val name: kotlin.String,
    /* Url of the profile picture of the friend */
    val pictureUuid: kotlin.String? = null
) 

