/**
* Pictural API
* This API is part of my project for the Shopify Developer intern challenge. This API manage the users, pictures and links between accounts of Pictural.
*
* The version of the OpenAPI document: 0.1.0
* Contact: chretienxavier42@gmail.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.xavierc.pictural.api.models


/**
 * 
 * @param uuid UUID of the image
 * @param ownerUuid UUID of the owner of the image
 * @param url Url to access the image
 * @param authorized List of UUID. Each UUID correspond to someone who has access at this image.
 * @param extensionType Extension type of the image
 */
data class ImageInfo (
    /* UUID of the image */
    val uuid: java.util.UUID,
    /* UUID of the owner of the image */
    val ownerUuid: String,
    /* List of UUID. Each UUID correspond to someone who has access at this image. */
    val authorized: List<String>,
    /* Extension type of the image */
    val extensionType: String
) 

