/**
* Pictural API
* This API is part of my project for the Shopify Developer intern challenge. This API manage the users, pictures and links between accounts of Pictural.
*
* The version of the OpenAPI document: 0.1.0
* Contact: chretienxavier42@gmail.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.xavierc.pictural.api.models


/**
 * 
 * @param name Name of the user
 * @param email email of the user
 */
data class InlineObject (
    /* Name of the user */
    val name: kotlin.String,
    /* email of the user */
    val email: kotlin.String
) 

