/**
* Pictural API
* This API is part of my project for the Shopify Developer intern challenge. This API manage the users, pictures and links between accounts of Pictural.
*
* The version of the OpenAPI document: 0.1.0
* Contact: chretienxavier42@gmail.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.xavierc.pictural.api.models

import dev.xavierc.pictural.api.models.Friend

/**
 * Response of a search request
 * @param usersMatch: list of user that match the string passed in parameter.
 */
data class SearchResponse (
    val usersMatch: List<Friend>? = null
) 

