/**
* Pictural API
* This API is part of my project for the Shopify Developer intern challenge. This API manage the users, pictures and links between accounts of Pictural.
*
* The version of the OpenAPI document: 0.1.0
* Contact: chretienxavier42@gmail.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.xavierc.pictural.api.models

import java.util.*

/**
 * 
 * @param uuid UUID of the user
 * @param name Name of the user
 * @param darkModeEnabled If the dark mode is enabled for the UI
 * @param pictureUuid Uuid of the profile picture of the user
 */
data class User(
    /* UUID of the user */
    val uuid: String,
    /* Name of the user */
    val name: String,
    /* If the dark mode is enabled for the UI */
    val darkModeEnabled: Boolean? = null,
    /* Url of the profile picture of the user */
    val pictureUuid: UUID? = null
)
