/**
 * Pictural API
 * This API is part of my project for the Shopify Developer intern challenge. This API manage the users, pictures and links between accounts of Pictural.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: chretienxavier42@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package dev.xavierc.pictural.api.apis

import com.google.gson.Gson
import io.ktor.application.call
import io.ktor.auth.authentication
import io.ktor.auth.authenticate
import io.ktor.auth.OAuthAccessTokenResponse
import io.ktor.http.ContentType
import io.ktor.http.HttpStatusCode
import io.ktor.response.respond
import io.ktor.response.respondText
import io.ktor.routing.Route
import io.ktor.routing.post
import io.ktor.routing.put
import io.ktor.routing.route

import dev.xavierc.pictural.api.Paths
import dev.xavierc.pictural.api.models.AlbumsListResponse
import dev.xavierc.pictural.api.models.ImageInfo
import dev.xavierc.pictural.api.repository.AlbumRepository
import io.ktor.locations.*
import io.ktor.sessions.*
import org.kodein.di.instance
import org.kodein.di.ktor.di

@KtorExperimentalLocationsAPI
fun Route.AlbumApi() {
    val gson = Gson()
    val empty = mutableMapOf<String, Any?>()

    val albumRepository by di().instance<AlbumRepository>()

    post { request: Paths.AlbumAdd ->
        val userUuid = call.sessions.get("userUuid") as String?

        if (userUuid == null) {
            call.respond(HttpStatusCode.Unauthorized)
        } else {
            call.respond(HttpStatusCode.NotImplemented)
        }
    }

    delete { _: Paths.AlbumDelete ->
        val userUuid = call.sessions.get("userUuid") as String?

        if (userUuid == null) {
            call.respond(HttpStatusCode.Unauthorized)
        } else {
            call.respond(HttpStatusCode.NotImplemented)
        }
    }


    route("/album") {
        put {
            val userUuid = call.sessions.get("userUuid") as String?

            if (userUuid == null) {
                call.respond(HttpStatusCode.Unauthorized)
            } else {
                call.respond(HttpStatusCode.NotImplemented)
            }
        }
    }


    get { _: Paths.AlbumsGet ->
        val userUuid = call.sessions.get("userUuid") as String?

        if (userUuid == null) {
            call.respond(HttpStatusCode.Unauthorized)
        } else {
            val albums = albumRepository.getAlbums(userUuid)

            call.respond(HttpStatusCode.OK, AlbumsListResponse(albums))
        }
    }
}
